# Generated by Django 6.0.5 on 2026-06-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupidea',
            name='problem',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startupidea',
            name='revenue_model',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startupidea',
            name='startup_stage',
            field=models.CharField(default='Idea', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startupidea',
            name='target_audience',
            field=models.CharField(default='General users', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='startupidea',
            name='usp',
            field=models.TextField(default='No USP specified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startupidea',
            name='industry',
            field=models.CharField(max_length=100),
        ),
    ]
