# Generated by Django 6.0.5 on 2026-06-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_startupidea_problem_startupidea_revenue_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupidea',
            name='business_model',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='competitors',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='funding',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='improvements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='market',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='name_suggestions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='opportunities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='pitch',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='risk',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='score',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='strengths',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='tagline',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='tam_sam_som',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='threats',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='weaknesses',
            field=models.TextField(blank=True, default=''),
        ),
    ]
