# Generated by Django 6.0.5 on 2026-06-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_startupidea_user'),
        ('validator', '0003_startupidea_business_model_startupidea_competitors_and_more'),
    ]

    operations = [
    ]
