# Generated by Django 6.0.5 on 2026-06-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0004_merge_20260603_1713'),
        ('validator', '0004_merge_20260603_1747'),
    ]

    operations = [
    ]
