# Generated by Django 6.0.5 on 2026-06-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0005_merge_20260607_1921'),
        ('validator', '0005_merge_20260607_2024'),
    ]

    operations = [
    ]
